In [9]:
import numpy as np
import pandas as pd

In [10]:
df=pd.read_csv('covid_toy.csv')

In [11]:
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [12]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid'], axis=1), df['has_covid'], test_size=0.2, random_state=42)

In [14]:
x_train.head()

    age  gender  fever cough     city
55   81  Female  101.0  Mild   Mumbai
88    5  Female  100.0  Mild  Kolkata
26   19  Female  100.0  Mild  Kolkata
42   27    Male  100.0  Mild    Delhi
69   73  Female  103.0  Mild    Delhi

In [15]:
x_test.head()

    age  gender  fever   cough       city
83   17  Female  104.0    Mild    Kolkata
53   83    Male   98.0    Mild      Delhi
70   68  Female  101.0  Strong      Delhi
45   72    Male   99.0    Mild  Bangalore
44   20    Male  102.0  Strong      Delhi

In [16]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

 using column transformer to apply different transformations
not needed to use each transformation on each column separately, we can use column transformer to apply different transformations on different columns

Demonstrating without colm transfer

In [ ]:
# add simple imputer to fill missing values in the 'fever' column with the mean value of that column
si=SimpleImputer(strategy='mean')
X_train_fever=si.fit_transform(x_train[['fever']])

x_test_fever=si.transform(x_test[['fever']])

X_train_fever

array([[101.],
       [100.],
       [100.],
       [100.],
       [103.],
       [103.],
       [102.],
       [101.],
       [101.],
       [101.],
       [ 98.],
       [104.],
       [103.],
       [104.],
       [100.],
       [101.],
       [104.],
       [102.],
       [102.],
       [103.],
       [104.],
       [102.],
       [101.],
       [104.],
       [102.],
       [101.],
       [ 99.],
       [101.],
       [104.],
       [102.],
       [100.],
       [ 98.],
       [ 98.],
       [101.],
       [100.],
       [100.],
       [101.],
       [104.],
       [101.],
       [103.],
       [101.],
       [ 98.],
       [ 99.],
       [ 99.],
       [101.],
       [ 99.],
       [101.],
       [104.],
       [ 98.],
       [101.],
       [103.],
       [101.],
       [ 98.],
       [ 99.],
       [ 98.],
       [ 99.],
       [102.],
       [101.],
       [101.],
       [104.],
       [100.],
       [ 98.],
       [100.],
       [101.],
       [100.],
       [100.],
       [ 98.],
       [101.],
       [ 98.],
       [101.],
       [101.],
       [104.],
       [104.],
       [ 98.],
       [ 98.],
       [102.],
       [104.],
       [104.],
       [102.],
       [100.]])

In [21]:
X_train_fever.shape

(80, 1)

In [22]:
# ordinal encoding -> cough

In [23]:
oe=OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough=oe.fit_transform(x_train[['cough']])
x_test_cough=oe.transform(x_test[['cough']])

In [ ]:
x_train_cough
# 0 is for Mild and 1 is for Strong

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.]])

In [26]:
df['city'].unique()

array(['Kolkata', 'Delhi', 'Mumbai', 'Bangalore'], dtype=object)

In [ ]:
# one hot enocding -> gender and city
# the first category is dropped to avoid dummy variable trap

ohe=OneHotEncoder( drop='first',sparse_output=False)

X_train_gender_city = ohe.fit_transform(x_train[['gender','city']])

X_test_gender_city = ohe.transform(x_test[['gender','city']])

In [36]:
X_train_gender_city.shape

(80, 4)

In [37]:
X_train_gender_city

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.]])

In [38]:
x_train_age=x_train.drop(columns=['fever','cough','gender','city'],axis=1)
x_test_age=x_test.drop(columns=['fever','cough','gender','city'],axis=1)

x_train_age.shape

(80, 1)

In [39]:
x_train_transformed=np.concatenate([X_train_fever,x_train_cough,X_train_gender_city,x_train_age],axis=1)
x_test_transformed=np.concatenate([x_test_fever,x_test_cough,X_test_gender_city,x_test_age],axis=1)

In [40]:
x_train_transformed.shape

(80, 7)

In [42]:
x_train_transformed

array([[101.,   0.,   0.,   0.,   0.,   1.,  81.],
       [100.,   0.,   0.,   0.,   1.,   0.,   5.],
       [100.,   0.,   0.,   0.,   1.,   0.,  19.],
       [100.,   0.,   1.,   1.,   0.,   0.,  27.],
       [103.,   0.,   0.,   1.,   0.,   0.,  73.],
       [103.,   1.,   1.,   0.,   1.,   0.,  70.],
       [102.,   0.,   0.,   1.,   0.,   0.,  49.],
       [101.,   1.,   0.,   0.,   1.,   0.,  51.],
       [101.,   0.,   0.,   1.,   0.,   0.,  64.],
       [101.,   0.,   0.,   0.,   1.,   0.,  83.],
       [ 98.,   0.,   0.,   0.,   0.,   1.,  65.],
       [104.,   0.,   0.,   0.,   0.,   0.,  18.],
       [103.,   0.,   0.,   0.,   0.,   0.,  16.],
       [104.,   0.,   1.,   0.,   1.,   0.,  16.],
       [100.,   0.,   1.,   0.,   1.,   0.,  27.],
       [101.,   0.,   0.,   0.,   0.,   0.,  84.],
       [104.,   0.,   1.,   0.,   1.,   0.,  51.],
       [102.,   0.,   0.,   0.,   0.,   0.,  69.],
       [102.,   1.,   0.,   0.,   0.,   0.,  82.],
       [103.,   0.,   0.,   0.,   1.,   0.,  69.],
       [104.,   0.,   1.,   0.,   0.,   1.,  44.],
       [102.,   0.,   1.,   0.,   0.,   1.,  74.],
       [101.,   1.,   0.,   0.,   0.,   1.,  20.],
       [104.,   0.,   0.,   0.,   0.,   0.,  12.],
       [102.,   1.,   0.,   1.,   0.,   0.,  33.],
       [101.,   1.,   0.,   0.,   0.,   0.,  42.],
       [ 99.,   0.,   1.,   1.,   0.,   0.,  65.],
       [101.,   0.,   1.,   0.,   0.,   1.,  23.],
       [104.,   1.,   0.,   0.,   0.,   0.,  56.],
       [102.,   0.,   1.,   0.,   0.,   0.,  64.],
       [100.,   1.,   0.,   0.,   1.,   0.,  13.],
       [ 98.,   0.,   0.,   0.,   1.,   0.,  31.],
       [ 98.,   1.,   0.,   1.,   0.,   0.,  40.],
       [101.,   0.,   0.,   1.,   0.,   0.,  49.],
       [100.,   1.,   0.,   0.,   0.,   0.,  19.],
       [100.,   0.,   1.,   0.,   0.,   0.,  11.],
       [101.,   1.,   1.,   0.,   0.,   0.,  14.],
       [104.,   0.,   1.,   0.,   0.,   1.,  42.],
       [101.,   0.,   0.,   0.,   0.,   0.,  38.],
       [103.,   1.,   1.,   0.,   0.,   0.,  46.],
       [101.,   1.,   1.,   0.,   1.,   0.,  71.],
       [ 98.,   1.,   0.,   0.,   1.,   0.,  10.],
       [ 99.,   0.,   0.,   0.,   0.,   1.,  60.],
       [ 99.,   0.,   0.,   0.,   0.,   0.,  22.],
       [101.,   0.,   1.,   1.,   0.,   0.,  19.],
       [ 99.,   0.,   1.,   0.,   0.,   0.,  65.],
       [101.,   0.,   0.,   0.,   0.,   1.,  19.],
       [104.,   1.,   0.,   0.,   1.,   0.,  54.],
       [ 98.,   1.,   0.,   0.,   0.,   1.,  81.],
       [101.,   0.,   0.,   0.,   0.,   0.,  20.],
       [103.,   0.,   0.,   0.,   1.,   0.,  48.],
       [101.,   0.,   1.,   0.,   1.,   0.,  82.],
       [ 98.,   1.,   1.,   0.,   0.,   1.,  23.],
       [ 99.,   1.,   1.,   0.,   0.,   0.,  66.],
       [ 98.,   1.,   0.,   0.,   0.,   1.,   5.],
       [ 99.,   1.,   0.,   0.,   0.,   0.,  49.],
       [102.,   0.,   1.,   0.,   1.,   0.,   5.],
       [101.,   1.,   0.,   1.,   0.,   0.,  34.],
       [101.,   1.,   1.,   0.,   1.,   0.,  79.],
       [104.,   0.,   0.,   0.,   1.,   0.,   6.],
       [100.,   0.,   1.,   0.,   0.,   0.,  10.],
       [ 98.,   1.,   0.,   0.,   0.,   1.,  69.],
       [100.,   0.,   1.,   0.,   1.,   0.,  55.],
       [101.,   1.,   0.,   0.,   0.,   1.,  34.],
       [100.,   0.,   1.,   1.,   0.,   0.,  27.],
       [100.,   1.,   0.,   0.,   0.,   0.,  47.],
       [ 98.,   0.,   1.,   0.,   0.,   0.,  73.],
       [101.,   0.,   1.,   1.,   0.,   0.,  42.],
       [ 98.,   0.,   0.,   1.,   0.,   0.,  80.],
       [101.,   1.,   1.,   0.,   0.,   0.,  47.],
       [101.,   0.,   1.,   1.,   0.,   0.,  38.],
       [104.,   1.,   0.,   1.,   0.,   0.,  34.],
       [104.,   0.,   1.,   0.,   0.,   0.,  25.],
       [ 98.,   0.,   1.,   0.,   1.,   0.,  24.],
       [ 98.,   1.,   1.,   0.,   0.,   0.,  12.],
       [102.,   1.,   0.,   0.,   0.,   0.,  24.],
       [104.,   1.,   0.,   1.,   0.,   0.,  75.],
       [104.,   0.,   1.,   0.,   0.,   0.,  51.],
       [102.,   1.,   0.,   0.,   1.,   0.,  82.],
       [100.,   1.,   0.,   0.,   1.,   0.,  11.]])

 Using column transformer

In [44]:
from sklearn.compose import ColumnTransformer

In [45]:
transformer=ColumnTransformer(transformers=[
    ('fever_imputer',SimpleImputer(strategy='mean'),['fever']),
    ('cough_encoder',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('gender_city_encoder',OneHotEncoder(drop='first',sparse_output=False),['gender','city'])
],remainder='passthrough')

In [47]:
transformer.fit_transform(x_train).shape

(80, 7)

In [48]:
transformer.fit_transform(x_train)

array([[101.,   0.,   0.,   0.,   0.,   1.,  81.],
       [100.,   0.,   0.,   0.,   1.,   0.,   5.],
       [100.,   0.,   0.,   0.,   1.,   0.,  19.],
       [100.,   0.,   1.,   1.,   0.,   0.,  27.],
       [103.,   0.,   0.,   1.,   0.,   0.,  73.],
       [103.,   1.,   1.,   0.,   1.,   0.,  70.],
       [102.,   0.,   0.,   1.,   0.,   0.,  49.],
       [101.,   1.,   0.,   0.,   1.,   0.,  51.],
       [101.,   0.,   0.,   1.,   0.,   0.,  64.],
       [101.,   0.,   0.,   0.,   1.,   0.,  83.],
       [ 98.,   0.,   0.,   0.,   0.,   1.,  65.],
       [104.,   0.,   0.,   0.,   0.,   0.,  18.],
       [103.,   0.,   0.,   0.,   0.,   0.,  16.],
       [104.,   0.,   1.,   0.,   1.,   0.,  16.],
       [100.,   0.,   1.,   0.,   1.,   0.,  27.],
       [101.,   0.,   0.,   0.,   0.,   0.,  84.],
       [104.,   0.,   1.,   0.,   1.,   0.,  51.],
       [102.,   0.,   0.,   0.,   0.,   0.,  69.],
       [102.,   1.,   0.,   0.,   0.,   0.,  82.],
       [103.,   0.,   0.,   0.,   1.,   0.,  69.],
       [104.,   0.,   1.,   0.,   0.,   1.,  44.],
       [102.,   0.,   1.,   0.,   0.,   1.,  74.],
       [101.,   1.,   0.,   0.,   0.,   1.,  20.],
       [104.,   0.,   0.,   0.,   0.,   0.,  12.],
       [102.,   1.,   0.,   1.,   0.,   0.,  33.],
       [101.,   1.,   0.,   0.,   0.,   0.,  42.],
       [ 99.,   0.,   1.,   1.,   0.,   0.,  65.],
       [101.,   0.,   1.,   0.,   0.,   1.,  23.],
       [104.,   1.,   0.,   0.,   0.,   0.,  56.],
       [102.,   0.,   1.,   0.,   0.,   0.,  64.],
       [100.,   1.,   0.,   0.,   1.,   0.,  13.],
       [ 98.,   0.,   0.,   0.,   1.,   0.,  31.],
       [ 98.,   1.,   0.,   1.,   0.,   0.,  40.],
       [101.,   0.,   0.,   1.,   0.,   0.,  49.],
       [100.,   1.,   0.,   0.,   0.,   0.,  19.],
       [100.,   0.,   1.,   0.,   0.,   0.,  11.],
       [101.,   1.,   1.,   0.,   0.,   0.,  14.],
       [104.,   0.,   1.,   0.,   0.,   1.,  42.],
       [101.,   0.,   0.,   0.,   0.,   0.,  38.],
       [103.,   1.,   1.,   0.,   0.,   0.,  46.],
       [101.,   1.,   1.,   0.,   1.,   0.,  71.],
       [ 98.,   1.,   0.,   0.,   1.,   0.,  10.],
       [ 99.,   0.,   0.,   0.,   0.,   1.,  60.],
       [ 99.,   0.,   0.,   0.,   0.,   0.,  22.],
       [101.,   0.,   1.,   1.,   0.,   0.,  19.],
       [ 99.,   0.,   1.,   0.,   0.,   0.,  65.],
       [101.,   0.,   0.,   0.,   0.,   1.,  19.],
       [104.,   1.,   0.,   0.,   1.,   0.,  54.],
       [ 98.,   1.,   0.,   0.,   0.,   1.,  81.],
       [101.,   0.,   0.,   0.,   0.,   0.,  20.],
       [103.,   0.,   0.,   0.,   1.,   0.,  48.],
       [101.,   0.,   1.,   0.,   1.,   0.,  82.],
       [ 98.,   1.,   1.,   0.,   0.,   1.,  23.],
       [ 99.,   1.,   1.,   0.,   0.,   0.,  66.],
       [ 98.,   1.,   0.,   0.,   0.,   1.,   5.],
       [ 99.,   1.,   0.,   0.,   0.,   0.,  49.],
       [102.,   0.,   1.,   0.,   1.,   0.,   5.],
       [101.,   1.,   0.,   1.,   0.,   0.,  34.],
       [101.,   1.,   1.,   0.,   1.,   0.,  79.],
       [104.,   0.,   0.,   0.,   1.,   0.,   6.],
       [100.,   0.,   1.,   0.,   0.,   0.,  10.],
       [ 98.,   1.,   0.,   0.,   0.,   1.,  69.],
       [100.,   0.,   1.,   0.,   1.,   0.,  55.],
       [101.,   1.,   0.,   0.,   0.,   1.,  34.],
       [100.,   0.,   1.,   1.,   0.,   0.,  27.],
       [100.,   1.,   0.,   0.,   0.,   0.,  47.],
       [ 98.,   0.,   1.,   0.,   0.,   0.,  73.],
       [101.,   0.,   1.,   1.,   0.,   0.,  42.],
       [ 98.,   0.,   0.,   1.,   0.,   0.,  80.],
       [101.,   1.,   1.,   0.,   0.,   0.,  47.],
       [101.,   0.,   1.,   1.,   0.,   0.,  38.],
       [104.,   1.,   0.,   1.,   0.,   0.,  34.],
       [104.,   0.,   1.,   0.,   0.,   0.,  25.],
       [ 98.,   0.,   1.,   0.,   1.,   0.,  24.],
       [ 98.,   1.,   1.,   0.,   0.,   0.,  12.],
       [102.,   1.,   0.,   0.,   0.,   0.,  24.],
       [104.,   1.,   0.,   1.,   0.,   0.,  75.],
       [104.,   0.,   1.,   0.,   0.,   0.,  51.],
       [102.,   1.,   0.,   0.,   1.,   0.,  82.],
       [100.,   1.,   0.,   0.,   1.,   0.,  11.]])

In [50]:
transformer.transform(x_test).shape

(20, 7)

In [52]:
transformer.transform(x_test)

array([[104.,   0.,   0.,   0.,   1.,   0.,  17.],
       [ 98.,   0.,   1.,   1.,   0.,   0.,  83.],
       [101.,   1.,   0.,   1.,   0.,   0.,  68.],
       [ 99.,   0.,   1.,   0.,   0.,   0.,  72.],
       [102.,   1.,   1.,   1.,   0.,   0.,  20.],
       [103.,   0.,   0.,   0.,   1.,   0.,  50.],
       [ 98.,   1.,   0.,   0.,   1.,   0.,  71.],
       [ 99.,   0.,   0.,   0.,   0.,   1.,  14.],
       [101.,   0.,   0.,   1.,   0.,   0.,  75.],
       [103.,   0.,   1.,   0.,   1.,   0.,  60.],
       [ 98.,   0.,   0.,   0.,   0.,   0.,  64.],
       [101.,   0.,   1.,   1.,   0.,   0.,  15.],
       [ 98.,   1.,   1.,   0.,   1.,   0.,  34.],
       [ 98.,   0.,   0.,   0.,   1.,   0.,  26.],
       [ 99.,   1.,   0.,   1.,   0.,   0.,  59.],
       [101.,   0.,   0.,   0.,   0.,   1.,  65.],
       [100.,   0.,   1.,   0.,   0.,   0.,  80.],
       [101.,   0.,   0.,   0.,   1.,   0.,   8.],
       [ 99.,   1.,   0.,   0.,   1.,   0.,  25.],
       [103.,   0.,   1.,   0.,   1.,   0.,  83.]])